#!/usr/bin/env python3
# SPDX-License-Identifier: AGPL-3.0-only
"""Write kernel/refusals.mjs from the compiler source: the Sanskrit refusal names, copied, never typed.
usage: tools/gen-refusals.py <path to crates/sadhana-t1/src/ir.t1 of paramtatv/sassembly v1.0.1>
A name is the public constant `सार्वजनिक चरः <NAME> ॱॱ न६४ भवति <decimal code> ।` for finisher codes 0x355, 0x35c, 0x35d, 0x35e."""
import re, sys, os
D = str.maketrans('०१२३४५६७८९', '0123456789')
want = {0x355, 0x35c, 0x35d, 0x35e}
found = {}
for line in open(sys.argv[1], encoding='utf8'):
    m = re.match(r'सार्वजनिक चरः (\S+) ॱॱ न६४ भवति ([०-९]+) ।', line)
    if m and int(m.group(2).translate(D)) in want:
        found[int(m.group(2).translate(D))] = m.group(1)
assert set(found) == want, found
out = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'kernel', 'refusals.mjs')
with open(out, 'w', encoding='utf8') as f:
    f.write('// SPDX-License-Identifier: AGPL-3.0-only\n')
    f.write('// GENERATED by tools/gen-refusals.py from ir.t1 of paramtatv/sassembly v1.0.1. Do not edit.\n')
    f.write('// Finisher status -> the refusal name, as the compiler source spells it.\nexport const REFUSALS = {\n')
    for k in sorted(found): f.write(f"  {k}: '{found[k]}',  // 0x{k:x}\n")
    f.write('};\n')
