#!/usr/bin/env python3
# SPDX-License-Identifier: AGPL-3.0-only
"""Write kernel/isas-names.mjs: the .isas marker words, COPIED from the format spec, never retyped.
usage: tools/gen-isas-names.py <isas-format.md>   (the line `Owner-ruled names ...: A · B · C` and the marker line)"""
import re, sys, os
t = open(sys.argv[1], encoding='utf8').read()
bar = re.search(r'`(॥) कोष्ठः N', t).group(1)
m = re.search(r'Owner-ruled names[^:]*:\s*([^\n]+)', t).group(1)
cell, kind, out = [x.strip() for x in m.split('·')]
assert (cell, kind, out) == (cell, kind, out) and all(re.fullmatch(r'[ऀ-ॿ]+', x) for x in (cell, kind, out)), m
assert f'{bar} {cell} N {kind} {bar}' in t and f'{bar} {out} {bar}' in t
dst = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'kernel', 'isas-names.mjs')
open(dst, 'w', encoding='utf8').write(f"""// SPDX-License-Identifier: AGPL-3.0-only
// GENERATED by tools/gen-isas-names.py from the .isas format spec (owner-ruled names). Do not edit.
export const BAR = '{bar}', CELL = '{cell}', KIND = '{kind}', OUTPUT = '{out}';
""")
